### ISSUE TITLE
Broken link to github repo

### ISSUE THREAD

**Issue by colinl** [5minds/node-red-dashboard-2-processcube-dynamic-form#8]
There is a typo in the github link in package.json, which is used to link there from npmjs and the node-red flows site.
```
    "repository": {
        "type": "git",
        "url": "https://github.com/5minds/.gitnode-red-dashboard-2-processcube-dynamic-form"
    },
```
Should be 
`        "url": "https://github.com/5minds/node-red-dashboard-2-processcube-dynamic-form"`

**Comment by moellenbeck** [comment]
@colinl fixed. See https://flows.nodered.org/node/@5minds/node-red-dashboard-2-processcube-dynamic-form
